#!/usr/bin/env bash
# Script to create GitHub issues for ALL open and assigned tasks
# Generated by Planning Petra on 2025-11-26
# Organizes tasks into logical epics based on context and priority

set -euo pipefail

REPO="sddevelopment-be/quickstart_agent-augmented-development"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🏗️  Creating GitHub issues for all open/assigned tasks..."
echo ""

# Function to create an epic
create_epic() {
  local title="$1"
  local body="$2"
  local labels="${3:-epic,orchestration}"
  
  echo "📋 Creating Epic: $title..."
  
  local epic_number=$(bash "$REPO_ROOT/ops/scripts/create-github-issue.sh" \
    --repo "$REPO" \
    --title "$title" \
    --label "$labels" \
    --body "$body" 2>&1 | grep -oP '#\K[0-9]+' | head -1 || echo "")
  
  if [ -z "$epic_number" ]; then
    echo "⚠️  Could not extract epic number, continuing..."
    epic_number="UNKNOWN"
  else
    echo "✅ Epic created: #$epic_number"
  fi
  
  echo "$epic_number"
}

# Function to create an issue
create_issue() {
  local title="$1"
  local body="$2"
  local labels="$3"
  local epic_ref="$4"
  
  echo "📝 Creating: $title"
  
  # Add epic reference if provided
  if [ -n "$epic_ref" ] && [ "$epic_ref" != "UNKNOWN" ]; then
    body="${body}

---

**Part of Epic:** #${epic_ref}"
  fi
  
  bash "$REPO_ROOT/ops/scripts/create-github-issue.sh" \
    --repo "$REPO" \
    --title "$title" \
    --label "$labels" \
    --body "$body" || echo "⚠️  Failed to create: $title"
  
  echo ""
}

echo "═══════════════════════════════════════════════════════════"
echo " EPIC 1: Housekeeping and Refactoring (Already created)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This epic was already created by the previous script."
echo "Run: bash ops/scripts/create_housekeeping_issues.sh"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo " EPIC 2: POC3 Multi-Agent Chain"
echo "═══════════════════════════════════════════════════════════"
echo ""

POC3_EPIC=$(create_epic \
  "Epic: POC3 Multi-Agent Chain Validation" \
  "$(cat <<'EOF'
# POC3 Multi-Agent Chain Validation Epic

## Overview

Final validation proof-of-concept before declaring the orchestration system production-ready. Tests complete multi-agent chain with handoffs, metrics, and documentation.

## Context

- Created: 2025-11-23
- Purpose: Validate multi-agent collaboration and handoff patterns
- Chain: Architect → Diagrammer → Synthesizer → Writer-Editor → Curator
- Status: Partially complete, follow-up tasks remain

## Goals

- **Validate Handoffs**: Ensure seamless agent-to-agent task transitions
- **Test Metrics**: Verify ADR-009 metrics capture throughout chain
- **Documentation**: Complete documentation and accessibility updates
- **Quality Gates**: Curator final validation before production declaration

## Scope

Includes diagram updates, documentation synthesis, and final validation tasks from the POC3 chain.

## Success Criteria

- [ ] All POC3 follow-up tasks completed
- [ ] Diagrams updated with metrics visualization
- [ ] Documentation synthesized and reviewed
- [ ] Curator validation passed
- [ ] Metrics captured at each step
- [ ] Handoff pattern validated

## Timeline

**Target:** 1 week  
**Priority:** High (final validation before production)

## Related Work

- ADR-009: Orchestration Metrics Standard
- File-based orchestration implementation
- Previous POC iterations

---

_Created by: Planning Petra_  
_Date: 2025-11-26_
EOF
)" \
  "epic,poc,orchestration,high-priority")

echo ""

# POC3 Follow-up Issues
create_issue \
  "POC3: Update orchestration diagrams with metrics visualization" \
  "$(cat <<'EOF'
## Description

Update workflow diagrams with timing/metrics annotations and create metrics dashboard concept visualization.

## Context

- Task file: \`work/collaboration/inbox/2025-11-24T1756-diagrammer-followup-2025-11-23T1738-architect-poc3-multi-agent-chain.yaml\`
- Follow-up from architect POC3 multi-agent chain task
- Part of POC3 validation

## Acceptance Criteria

- [ ] Update \`workflow-sequential-flow.puml\` with timing/metrics annotations
- [ ] Create \`metrics-dashboard-concept.puml\` visualizing ADR-009 capture points
- [ ] Add accessibility descriptions to \`DESCRIPTIONS.md\`
- [ ] Follow ADR-009 standards (metrics block, per-artifact validation)
- [ ] Validate rendering or mark with ⚠️ if unverified

## Deliverables

- \`docs/architecture/diagrams/workflow-sequential-flow.puml\` (updated)
- \`docs/architecture/diagrams/metrics-dashboard-concept.puml\` (new)
- \`docs/architecture/diagrams/DESCRIPTIONS.md\` (updated)

**Agent:** diagrammer  
**Priority:** high
EOF
" \
  "poc,diagrams,diagrammer,high-priority" \
  "$POC3_EPIC")

create_issue \
  "POC3: Synthesize diagram updates and aggregate metrics" \
  "$(cat <<'EOF'
## Description

Synthesize information from completed POC3 diagram updates and create aggregate metrics report.

## Context

- Task file: \`work/collaboration/inbox/2025-11-24T1756-synthesizer-followup-2025-11-23T2100-diagrammer-poc3-diagram-updates.yaml\`
- Depends on diagrammer POC3 diagram updates completion
- Part of POC3 validation chain

## Acceptance Criteria

- [ ] Review completed diagram updates
- [ ] Synthesize key findings from POC3 chain
- [ ] Create aggregate metrics report
- [ ] Document lessons learned
- [ ] Prepare summary for writer-editor review

## Deliverables

- Synthesis report in \`work/reports/synthesizer/\`
- Aggregate metrics document
- Work log

**Agent:** synthesizer  
**Priority:** high  
**Depends on:** Diagrammer POC3 task completion
EOF
" \
  "poc,synthesizer,high-priority" \
  "$POC3_EPIC")

create_issue \
  "POC3: Review and polish orchestration guide documentation" \
  "$(cat <<'EOF'
## Description

Review orchestration guide following POC3 validation and polish documentation for clarity and completeness.

## Context

- Task file: \`work/collaboration/inbox/2025-11-24T1756-writer-editor-followup-2025-11-23T0722-curator-orchestration-guide.yaml\`
- Part of POC3 validation chain
- Ensures documentation quality before production

## Acceptance Criteria

- [ ] Review orchestration guide documentation
- [ ] Polish for clarity and accessibility
- [ ] Ensure consistency with POC3 findings
- [ ] Update examples if needed
- [ ] Verify cross-references

## Deliverables

- Updated orchestration guide documentation
- Work log documenting changes

**Agent:** writer-editor  
**Priority:** high
EOF
" \
  "poc,documentation,writer-editor,high-priority" \
  "$POC3_EPIC")

create_issue \
  "POC3: Review aggregate metrics synthesis" \
  "$(cat <<'EOF'
## Description

Review synthesizer's aggregate metrics report from POC3 and provide editorial feedback.

## Context

- Task file: \`work/collaboration/inbox/2025-11-24T1756-writer-editor-followup-2025-11-23T2117-synthesizer-poc3-aggregate-metrics.yaml\`
- Part of POC3 documentation validation
- Final review before curator validation

## Acceptance Criteria

- [ ] Review aggregate metrics report
- [ ] Provide editorial feedback
- [ ] Ensure clarity and accessibility
- [ ] Verify metric interpretations
- [ ] Polish for final presentation

## Deliverables

- Editorial review notes
- Polished metrics report (if changes needed)
- Work log

**Agent:** writer-editor  
**Priority:** normal  
**Depends on:** Synthesizer POC3 metrics task
EOF
" \
  "poc,documentation,writer-editor" \
  "$POC3_EPIC")

echo "═══════════════════════════════════════════════════════════"
echo " EPIC 3: Documentation and Directives"
echo "═══════════════════════════════════════════════════════════"
echo ""

DOCS_EPIC=$(create_epic \
  "Epic: Documentation and Directives Improvements" \
  "$(cat <<'EOF'
# Documentation and Directives Improvements Epic

## Overview

Consolidate various documentation improvement tasks including directive condensation, validation, and documentation updates.

## Context

- Multiple documentation tasks from different work streams
- Need for consistency and clarity improvements
- Directive optimization for better agent comprehension

## Goals

- **Consistency**: Ensure documentation is consistent across repository
- **Clarity**: Improve accessibility for contributors
- **Validation**: Verify directive accuracy and completeness
- **Optimization**: Condense verbose directives where appropriate

## Scope

Includes locality of change directive, primer validation, documentation updates, and general validation/refactoring.

## Success Criteria

- [ ] All directive condensation completed
- [ ] Validation tasks executed
- [ ] Documentation updated for new structures
- [ ] Cross-references verified

## Timeline

**Target:** 1-2 weeks  
**Priority:** Normal-High (quality improvements)

---

_Created by: Planning Petra_  
_Date: 2025-11-26_
EOF
)" \
  "epic,documentation,directives")

echo ""

create_issue \
  "Create condensed locality of change directive" \
  "$(cat <<'EOF'
## Description

Create a condensed version of the locality of change directive for better token efficiency and agent comprehension.

## Context

- Task file: \`work/collaboration/inbox/2025-11-24T1908-curator-locality-of-change-condensed-directive.yaml\`
- Created: 2025-11-24
- Part of directive optimization efforts

## Acceptance Criteria

- [ ] Review existing locality of change guidance
- [ ] Create condensed directive version
- [ ] Maintain core principles and practices
- [ ] Improve token efficiency
- [ ] Update cross-references

## Deliverables

- Condensed directive file
- Work log documenting changes

**Agent:** curator  
**Priority:** normal
EOF
" \
  "documentation,curator,directives" \
  "$DOCS_EPIC")

create_issue \
  "Validate primer directive implementation" \
  "$(cat <<'EOF'
## Description

Review and validate the primer directive to ensure proper implementation and effectiveness.

## Context

- Task file: \`work/collaboration/inbox/2025-11-24T1951-architect-primer-directive-validation.yaml\`
- Created: 2025-11-24
- Architectural validation task

## Acceptance Criteria

- [ ] Review primer directive documentation
- [ ] Validate implementation against requirements
- [ ] Test with sample scenarios
- [ ] Document findings and recommendations
- [ ] Create ADR if changes needed

## Deliverables

- Validation report
- ADR (if applicable)
- Work log

**Agent:** architect  
**Priority:** normal
EOF
" \
  "documentation,architect,directives" \
  "$DOCS_EPIC")

create_issue \
  "Validate and refactor documentation structure" \
  "$(cat <<'EOF'
## Description

General validation and refactoring task for documentation structure to ensure consistency and quality.

## Context

- Task file: \`work/collaboration/inbox/2025-11-25T1837-curator-validate-refactor.yaml\`
- Created: 2025-11-25
- General quality improvement

## Acceptance Criteria

- [ ] Review documentation structure
- [ ] Identify inconsistencies
- [ ] Refactor for improved organization
- [ ] Update cross-references
- [ ] Verify accessibility

## Deliverables

- Refactored documentation
- Validation report
- Work log

**Agent:** curator  
**Priority:** normal
EOF
" \
  "documentation,curator" \
  "$DOCS_EPIC")

create_issue \
  "Update documentation for new script organization" \
  "$(cat <<'EOF'
## Description

Update documentation to reflect new script organization and locations after automation script rework.

## Context

- Task file: \`work/collaboration/inbox/2025-11-25T1838-writer-editor-update-docs.yaml\`
- Branch: copilot/rework-automation-scripts
- Created: 2025-11-25

## Acceptance Criteria

- [ ] Update HOW_TO_USE guide with new script locations
- [ ] Document task_utils.py module if needed
- [ ] Update CONTRIBUTING.md for new paths
- [ ] Verify code examples use correct paths
- [ ] Ensure clarity for new contributors

## Deliverables

- \`docs/HOW_TO_USE/multi-agent-orchestration.md\` (updated)
- \`docs/CONTRIBUTING.md\` (updated if needed)
- Work log

**Agent:** writer-editor  
**Priority:** normal
EOF
" \
  "documentation,writer-editor" \
  "$DOCS_EPIC")

echo "═══════════════════════════════════════════════════════════"
echo " EPIC 4: Build Automation and CI/CD"
echo "═══════════════════════════════════════════════════════════"
echo ""

BUILD_EPIC=$(create_epic \
  "Epic: Build Automation and CI/CD Enhancements" \
  "$(cat <<'EOF'
# Build Automation and CI/CD Enhancements Epic

## Overview

Comprehensive build automation, testing, and CI/CD improvements to support the orchestration framework.

## Context

- Multiple build automation tasks from orchestration framework development
- Need for robust testing, validation, and deployment automation
- Security and performance considerations

## Goals

- **CI/CD**: Automated testing and validation workflows
- **Security**: Checksum verification and secure installations
- **Performance**: Parallel installation and telemetry
- **Templates**: Reusable GitHub issue templates
- **Testing**: Comprehensive test workflows

## Scope

Includes test workflows, security features, performance optimizations, telemetry collection, and GitHub issue templates.

## Success Criteria

- [ ] Test workflows operational
- [ ] Security checksum verification implemented
- [ ] Parallel installation working
- [ ] Telemetry collection active
- [ ] GitHub issue template created
- [ ] All automation validated

## Timeline

**Target:** 2-3 weeks  
**Priority:** High (infrastructure)

---

_Created by: Planning Petra_  
_Date: 2025-11-26_
EOF
)" \
  "epic,build-automation,ci-cd,high-priority")

echo ""

create_issue \
  "Implement test workflows for automation scripts" \
  "$(cat <<'EOF'
## Description

Create comprehensive test workflows to validate automation scripts after rework.

## Context

- Task file: \`work/collaboration/inbox/2025-11-25T1839-build-automation-test-workflows.yaml\`
- Branch: copilot/rework-automation-scripts
- Created: 2025-11-25

## Acceptance Criteria

- [ ] Create test workflows for automation scripts
- [ ] Validate task_utils.py module
- [ ] Test orchestrator script
- [ ] Verify error handling
- [ ] Document test coverage

## Deliverables

- Test workflow files
- Test documentation
- Coverage report
- Work log

**Agent:** build-automation  
**Priority:** high
EOF
" \
  "build-automation,testing,ci-cd,high-priority" \
  "$BUILD_EPIC")

create_issue \
  "Create 'Run Iteration' GitHub issue template" \
  "$(cat <<'EOF'
## Description

Create GitHub issue template for running orchestration iterations, enabling automated/repeatable execution.

## Context

- Task file: \`work/collaboration/assigned/build-automation/2025-11-23T2204-build-automation-run-iteration-issue.yaml\`
- Requested in PR #24 comments
- Status: assigned

## Acceptance Criteria

- [ ] Issue template created in \`.github/ISSUE_TEMPLATE/run-iteration.md\`
- [ ] YAML frontmatter with correct metadata
- [ ] All required sections included
- [ ] Clear execution instructions
- [ ] Success criteria with checkboxes
- [ ] Framework documentation references
- [ ] Example prompt provided
- [ ] Template is reusable
- [ ] Work log created per Directive 014

## Deliverables

- \`.github/ISSUE_TEMPLATE/run-iteration.md\`
- Work log

**Agent:** build-automation  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "build-automation,templates,orchestration" \
  "$BUILD_EPIC")

# Additional assigned build-automation tasks
create_issue \
  "Implement security checksum verification for tooling" \
  "$(cat <<'EOF'
## Description

Add security checksum verification to tooling installation scripts to ensure integrity.

## Context

- Task file: \`work/collaboration/assigned/build-automation/2025-11-24T0949-build-automation-security-checksum-verification.yaml\`
- Status: assigned
- Security enhancement

## Acceptance Criteria

- [ ] Implement checksum verification for downloads
- [ ] Add SHA256 hash validation
- [ ] Document security process
- [ ] Test verification failures
- [ ] Update installation scripts
- [ ] Work log created

## Deliverables

- Updated installation scripts with checksum verification
- Security documentation
- Work log

**Agent:** build-automation  
**Priority:** high  
**Status:** assigned
EOF
" \
  "build-automation,security,high-priority" \
  "$BUILD_EPIC")

create_issue \
  "Implement parallel installation for tooling setup" \
  "$(cat <<'EOF'
## Description

Optimize tooling installation by implementing parallel download and installation where safe.

## Context

- Task file: \`work/collaboration/assigned/build-automation/2025-11-24T0953-build-automation-parallel-installation.yaml\`
- Status: assigned
- Performance optimization

## Acceptance Criteria

- [ ] Identify independent installation steps
- [ ] Implement parallel execution
- [ ] Maintain proper error handling
- [ ] Test installation reliability
- [ ] Document performance improvements
- [ ] Work log created

## Deliverables

- Optimized installation scripts
- Performance benchmarks
- Work log

**Agent:** build-automation  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "build-automation,performance" \
  "$BUILD_EPIC")

create_issue \
  "Implement telemetry collection for tooling setup" \
  "$(cat <<'EOF'
## Description

Add telemetry collection to track tooling setup success rates, timing, and failures for continuous improvement.

## Context

- Task file: \`work/collaboration/assigned/build-automation/2025-11-24T0954-build-automation-telemetry-collection.yaml\`
- Status: assigned
- Observability enhancement

## Acceptance Criteria

- [ ] Design telemetry data model
- [ ] Implement collection points
- [ ] Store telemetry data appropriately
- [ ] Create telemetry dashboard/report
- [ ] Document privacy considerations
- [ ] Work log created

## Deliverables

- Telemetry collection implementation
- Dashboard or reporting tool
- Privacy documentation
- Work log

**Agent:** build-automation  
**Priority:** low  
**Status:** assigned
EOF
" \
  "build-automation,telemetry" \
  "$BUILD_EPIC")

echo "═══════════════════════════════════════════════════════════"
echo " EPIC 5: Architectural Assessments and Planning"
echo "═══════════════════════════════════════════════════════════"
echo ""

ARCH_EPIC=$(create_epic \
  "Epic: Architectural Assessments and Strategic Planning" \
  "$(cat <<'EOF'
# Architectural Assessments and Strategic Planning Epic

## Overview

Strategic architectural assessments to guide future development and optimization efforts.

## Context

- Multiple architectural assessment tasks assigned
- Need for framework efficiency analysis
- Version policy documentation
- Tool coordination planning

## Goals

- **Efficiency**: Assess framework quality-to-cost ratio trends
- **Policy**: Document version governance and policies
- **Coordination**: Plan tooling enhancements coordination
- **Strategy**: Guide future optimization efforts

## Scope

Includes framework efficiency assessment, version policy documentation, and tooling enhancements coordination planning.

## Success Criteria

- [ ] Framework efficiency trends documented in ADR
- [ ] Version policy clearly documented
- [ ] Tooling enhancements coordinated
- [ ] Recommendations provided for optimizations

## Timeline

**Target:** 2-3 weeks  
**Priority:** Normal-Low (strategic planning)

---

_Created by: Planning Petra_  
_Date: 2025-11-26_
EOF
)" \
  "epic,architecture,planning")

echo ""

create_issue \
  "Assess agentic framework efficiency trends" \
  "$(cat <<'EOF'
## Description

Review aggregated token metrics and assess whether the agentic framework is improving in quality-to-cost ratio over time.

## Context

- Task file: \`work/collaboration/assigned/architect/2025-11-24T1736-architect-framework-efficiency-assessment.yaml\`
- Status: assigned
- Depends on synthesizer token metrics task
- Priority: low

## Acceptance Criteria

- [ ] Analyze token usage trends over time
- [ ] Compare early vs recent task efficiency
- [ ] Assess framework overhead trends
- [ ] Provide actionable recommendations
- [ ] Document in ADR-012
- [ ] Work log created per Directive 014

## Deliverables

- \`docs/architecture/adrs/ADR-012-framework-efficiency-trends.md\`
- Work log

**Agent:** architect  
**Priority:** low  
**Status:** assigned  
**Depends on:** Synthesizer token metrics aggregation
EOF
" \
  "architecture,architect,assessment" \
  "$ARCH_EPIC")

create_issue \
  "Document version policy and governance" \
  "$(cat <<'EOF'
## Description

Create comprehensive documentation of version policy and governance for the project.

## Context

- Task file: \`work/collaboration/assigned/architect/2025-11-24T0950-architect-version-policy-documentation.yaml\`
- Status: assigned
- Governance documentation

## Acceptance Criteria

- [ ] Document version numbering scheme
- [ ] Define release process
- [ ] Specify governance roles
- [ ] Clarify deprecation policy
- [ ] Document change management
- [ ] Work log created

## Deliverables

- Version policy documentation
- Governance guide
- Work log

**Agent:** architect  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "architecture,architect,governance" \
  "$ARCH_EPIC")

create_issue \
  "Coordinate tooling enhancements across agents" \
  "$(cat <<'EOF'
## Description

Meta-task to coordinate tooling enhancements and ensure consistency across agent implementations.

## Context

- Task file: \`work/collaboration/assigned/manager/2025-11-24T0955-manager-tooling-enhancements-coordination.yaml\`
- Status: assigned
- Cross-agent coordination

## Acceptance Criteria

- [ ] Review all tooling enhancement tasks
- [ ] Identify dependencies and conflicts
- [ ] Create coordination plan
- [ ] Assign priorities
- [ ] Track completion
- [ ] Work log created

## Deliverables

- Coordination plan
- Task tracking document
- Work log

**Agent:** manager  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "management,manager,coordination" \
  "$ARCH_EPIC")

echo "═══════════════════════════════════════════════════════════"
echo " EPIC 6: Curator Quality Tasks"
echo "═══════════════════════════════════════════════════════════"
echo ""

CURATOR_EPIC=$(create_epic \
  "Epic: Curator Quality and Maintenance Tasks" \
  "$(cat <<'EOF'
# Curator Quality and Maintenance Tasks Epic

## Overview

Curator-led quality improvements including changelog clarity, best practices guides, and maintenance checklist templates.

## Context

- Multiple curator tasks assigned for quality improvements
- Need for better documentation and maintenance processes
- Tooling best practices documentation

## Goals

- **Clarity**: Improve changelog readability and usefulness
- **Best Practices**: Document tooling setup best practices
- **Maintenance**: Create reusable maintenance checklist templates
- **Quality**: Ensure consistency and completeness

## Scope

Includes changelog improvements, best practices documentation, and maintenance template creation.

## Success Criteria

- [ ] Changelog clarity improved
- [ ] Tooling best practices documented
- [ ] Maintenance checklist templates created
- [ ] All documentation reviewed and validated

## Timeline

**Target:** 1-2 weeks  
**Priority:** Normal (quality improvements)

---

_Created by: Planning Petra_  
_Date: 2025-11-26_
EOF
)" \
  "epic,curator,quality")

echo ""

create_issue \
  "Improve changelog clarity and structure" \
  "$(cat <<'EOF'
## Description

Review and improve changelog for better clarity, structure, and usefulness to contributors.

## Context

- Task file: \`work/collaboration/assigned/curator/2025-11-24T0805-curator-changelog-clarity.yaml\`
- Status: assigned
- Quality improvement

## Acceptance Criteria

- [ ] Review current changelog structure
- [ ] Identify clarity issues
- [ ] Restructure for better readability
- [ ] Add missing categories if needed
- [ ] Ensure consistency
- [ ] Work log created

## Deliverables

- \`CHANGELOG.md\` (improved)
- Work log

**Agent:** curator  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "curator,documentation,quality" \
  "$CURATOR_EPIC")

create_issue \
  "Create tooling setup best practices guide" \
  "$(cat <<'EOF'
## Description

Document best practices for tooling setup to help agents and contributors set up development environments consistently.

## Context

- Task file: \`work/collaboration/assigned/curator/2025-11-24T0951-curator-tooling-best-practices-guide.yaml\`
- Status: assigned
- Documentation task

## Acceptance Criteria

- [ ] Document recommended tooling
- [ ] Provide setup instructions
- [ ] Include troubleshooting tips
- [ ] Add verification steps
- [ ] Reference Directive 013
- [ ] Work log created

## Deliverables

- Tooling best practices guide
- Work log

**Agent:** curator  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "curator,documentation,tooling" \
  "$CURATOR_EPIC")

create_issue \
  "Create maintenance checklist templates" \
  "$(cat <<'EOF'
## Description

Create reusable maintenance checklist templates to standardize routine maintenance tasks.

## Context

- Task file: \`work/collaboration/assigned/curator/2025-11-24T0952-curator-maintenance-checklist-templates.yaml\`
- Status: assigned
- Template creation

## Acceptance Criteria

- [ ] Identify common maintenance tasks
- [ ] Create checklist templates
- [ ] Document usage instructions
- [ ] Provide examples
- [ ] Store in templates directory
- [ ] Work log created

## Deliverables

- Maintenance checklist templates
- Usage documentation
- Work log

**Agent:** curator  
**Priority:** normal  
**Status:** assigned
EOF
" \
  "curator,templates,maintenance" \
  "$CURATOR_EPIC")

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "✅ Issue creation script completed!"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Created 6 epics:"
echo "  1. Housekeeping and Refactoring (run separate script)"
echo "  2. POC3 Multi-Agent Chain ($POC3_EPIC)"
echo "  3. Documentation and Directives ($DOCS_EPIC)"
echo "  4. Build Automation and CI/CD ($BUILD_EPIC)"
echo "  5. Architectural Assessments ($ARCH_EPIC)"
echo "  6. Curator Quality Tasks ($CURATOR_EPIC)"
echo ""
echo "Created approximately 20+ child issues across all epics"
echo ""
echo "Next steps:"
echo "1. Review created issues at https://github.com/$REPO/issues"
echo "2. Run housekeeping script: bash ops/scripts/create_housekeeping_issues.sh"
echo "3. Agents process tasks from work/collaboration/"
echo "4. Update epic progress as issues close"
