#!/usr/bin/env bash
# Script to create GitHub issues for Housekeeping and Refactoring epic
# Generated by Planning Petra on 2025-11-26

set -euo pipefail

REPO="sddevelopment-be/quickstart_agent-augmented-development"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🏗️  Creating Housekeeping and Refactoring Epic and related issues..."
echo ""

# Create Epic Issue
echo "📋 Creating Epic: Housekeeping and Refactoring..."
EPIC_BODY=$(cat <<'EOF'
# Housekeeping and Refactoring Epic

## Overview

This epic tracks ongoing housekeeping and refactoring work to improve the agent framework's maintainability, token efficiency, and developer experience.

## Context

Following the work directory restructuring, several follow-up tasks were identified to:
1. Reduce token consumption in verbose directives
2. Improve consistency across agent documentation
3. Enhance observability and monitoring capabilities
4. Assess future improvements to the orchestration system

## Goals

- **Token Efficiency**: Extract verbose directive content into modular approaches/templates
- **Consistency**: Create shared glossaries and improve cross-references
- **Observability**: Implement metric capture and dashboard capabilities
- **Future Planning**: Assess architectural improvements

## Scope

This epic includes refactoring existing directives, creating supporting infrastructure, and architectural assessments. It does NOT include new feature development.

## Success Criteria

- [ ] All verbose directives refactored with 50%+ token reduction
- [ ] Shared glossary created and integrated
- [ ] Metric capture scripts operational
- [ ] Dashboard files automatically generated
- [ ] Architectural assessments documented as ADRs

## Related Work

- Work directory restructuring PR
- Directive 019 refactoring (completed as template, commit 4c648e4)

## Timeline

**Target:** Complete within 2-3 weeks  
**Priority:** High (technical debt reduction)

## Child Issues

Will be created and linked below.

---

_Created by: Planning Petra_  
_Date: 2025-11-26_  
_Task files: work/collaboration/inbox/2025-11-26T06*.yaml_
EOF
)

EPIC_NUMBER=$(bash "$REPO_ROOT/ops/scripts/create-github-issue.sh" \
  --repo "$REPO" \
  --title "Epic: Housekeeping and Refactoring" \
  --label "epic" \
  --label "housekeeping" \
  --body "$EPIC_BODY" | grep -oP '#\K[0-9]+' || echo "")

if [ -z "$EPIC_NUMBER" ]; then
  echo "❌ Failed to create epic issue. Please check GH_TOKEN is set."
  exit 1
fi

echo "✅ Epic created: #$EPIC_NUMBER"
echo ""

# Helper function to create child issues
create_issue() {
  local title="$1"
  local labels="$2"
  local priority="$3"
  local body="$4"
  
  echo "📝 Creating: $title"
  
  # Add epic reference to body
  body="${body}

---

**Part of Epic:** #${EPIC_NUMBER}"
  
  bash "$REPO_ROOT/ops/scripts/create-github-issue.sh" \
    --repo "$REPO" \
    --title "$title" \
    --label "housekeeping" \
    --label "$labels" \
    --body "$body" || echo "⚠️  Failed to create issue: $title"
  
  echo ""
}

# Issue 1: Review Directive 009 and Create Shared Glossary
create_issue \
  "Review Directive 009 and consider shared glossary creation" \
  "documentation,architect" \
  "normal" \
  "$(cat <<'EOF'
## Description

Review Directive 009 (Role Capabilities) and the available agent profiles. Consider creating a shared glossary to help agents understand terminology consistently.

## Context

- Task file: \`work/collaboration/inbox/2025-11-26T0610-architect-review-directive-009-glossary.yaml\`
- PR comment: https://github.com/sddevelopment-be/quickstart_agent-augmented-development/pull/.../files#r2563266489

## Acceptance Criteria

- [ ] Directive 009 reviewed for accuracy and completeness
- [ ] Version governance reviewed (Directive 006)
- [ ] Decision made on shared glossary (create or defer)
- [ ] If creating glossary:
  - [ ] Format chosen (markdown, YAML, or JSON)
  - [ ] Glossary file created in \`data/\` directory
  - [ ] Directive 009 updated to reference glossary
  - [ ] Initial terminology entries populated
- [ ] Decision documented (ADR if deferring)

## Deliverables

- \`.github/agents/directives/009_role_capabilities.md\` (reviewed/updated)
- \`data/glossary.{md,yml,json}\` (if created)
- ADR documenting decision (if applicable)

**Agent:** architect  
**Priority:** normal
EOF
)"

# Issue 2: Extract Directive 013 to Approaches
create_issue \
  "Extract verbose content from Directive 013 to approaches directory" \
  "documentation,curator,high-priority" \
  "high" \
  "$(cat <<'EOF'
## Description

Directive 013 (Tooling Setup) is highly verbose with detailed approach descriptions. Extract these to modular approach files to improve token discipline.

## Context

- Task file: \`work/collaboration/inbox/2025-11-26T0611-curator-extract-directive-013-approaches.yaml\`
- Follows pattern from Directive 019 refactoring (70% token reduction, commit 4c648e4)
- PR comment: https://github.com/sddevelopment-be/quickstart_agent-augmented-development/pull/.../files#r2563281925

## Acceptance Criteria

- [ ] Directive 013 refactored to minimal format (~50-70% token reduction)
- [ ] Detailed content extracted to \`.github/agents/approaches/tooling_setup/\`
- [ ] One file per logical step/topic
- [ ] README.md created with overview and step index
- [ ] Directive updated with approach references
- [ ] Explicit guidance for on-demand loading included
- [ ] Work log created documenting changes

## Deliverables

- \`.github/agents/directives/013_tooling_setup.md\` (refactored)
- \`.github/agents/approaches/tooling_setup/README.md\`
- \`.github/agents/approaches/tooling_setup/*.md\` (extracted steps)
- \`work/reports/logs/curator/YYYY-MM-DDTHHMM-directive-013-refactoring.md\`

**Agent:** curator  
**Priority:** high
EOF
)"

# Issue 3: Extract Directive 015 to Templates
create_issue \
  "Extract verbose content from Directive 015 to docs/templates" \
  "documentation,curator,high-priority" \
  "high" \
  "$(cat <<'EOF'
## Description

Directive 015 (Store Prompts) is highly verbose with template content included inline. Extract templates to docs/templates for better organization and token efficiency.

## Context

- Task file: \`work/collaboration/inbox/2025-11-26T0612-curator-extract-directive-015-templates.yaml\`
- Follows pattern from Directive 019 refactoring (commit 4c648e4)
- PR comment: https://github.com/sddevelopment-be/quickstart_agent-augmented-development/pull/.../files#r2563290200

## Acceptance Criteria

- [ ] Directive 015 refactored to focus on when/how to use templates
- [ ] Template content extracted to \`docs/templates/prompt_templates/\`
- [ ] Each template in separate file with clear naming
- [ ] Directive updated with template references
- [ ] Token consumption reduced by ~50-70%
- [ ] Work log created documenting changes

## Deliverables

- \`.github/agents/directives/015_store_prompts.md\` (refactored)
- \`docs/templates/prompt_templates/*.md\` (extracted templates)
- \`docs/templates/prompt_templates/README.md\` (if needed)
- \`work/reports/logs/curator/YYYY-MM-DDTHHMM-directive-015-refactoring.md\`

**Agent:** curator  
**Priority:** high
EOF
)"

# Issue 4: Refactor Directive 018 for Token Efficiency
create_issue \
  "Refactor Directive 018 to reduce verbosity and extract sub-directives" \
  "documentation,curator,high-priority" \
  "high" \
  "$(cat <<'EOF'
## Description

Directive 018 (Traceable Decisions) is highly verbose. Extract specifics into sub-directives with a table informing agents when to load each.

## Context

- Task file: \`work/collaboration/inbox/2025-11-26T0613-curator-refactor-directive-018-verbosity.yaml\`
- More complex than other refactorings - may need subdirectory structure
- PR comment: https://github.com/sddevelopment-be/quickstart_agent-augmented-development/pull/.../files#r2563326044

## Acceptance Criteria

- [ ] Directive 018 refactored to overview format
- [ ] Sub-directives created in \`.github/agents/directives/traceable_decisions/\`
- [ ] Main directive includes table showing when to load each sub-directive
- [ ] Token consumption reduced by ~50-70%
- [ ] Cross-references maintained
- [ ] Work log created documenting changes

## Deliverables

- \`.github/agents/directives/018_traceable_decisions.md\` (refactored)
- \`.github/agents/directives/traceable_decisions/*.md\` (sub-directives)
- \`.github/agents/directives/traceable_decisions/README.md\` (if needed)
- \`work/reports/logs/curator/YYYY-MM-DDTHHMM-directive-018-refactoring.md\`

## Notes

Consider whether content belongs in \`directives/\` subdirectory vs \`approaches/\` directory.

**Agent:** curator  
**Priority:** high
EOF
)"

# Issue 5: Create Metric Capture Scripts and Dashboards
create_issue \
  "Create metric capture scripts and recreate collaboration dashboard files" \
  "infrastructure,build-automation,devops" \
  "normal" \
  "$(cat <<'EOF'
## Description

Create metric capture scripts to populate collaboration dashboard files. These dashboards provide visibility into agent orchestration activity.

## Context

- Task file: \`work/collaboration/inbox/2025-11-26T0615-build-automation-metric-capture-dashboard.yaml\`
- agent_base.py paths updated for new work directory structure
- PR comment: https://github.com/sddevelopment-be/quickstart_agent-augmented-development/pull/.../files#r2563371914

## Acceptance Criteria

- [ ] Metric capture script created: \`ops/scripts/metrics/capture_metrics.py\`
- [ ] Dashboard update script created: \`ops/scripts/metrics/update_dashboard.py\`
- [ ] Dashboard files recreated and auto-updated:
  - [ ] \`work/collaboration/AGENT_STATUS.md\`
  - [ ] \`work/collaboration/HANDOFFS.md\`
  - [ ] \`work/collaboration/WORKFLOW_LOG.md\`
- [ ] Scripts compatible with new \`work/collaboration/\` structure
- [ ] Scripts callable from orchestration system
- [ ] Documentation added for script usage
- [ ] Work log created

## Deliverables

- \`ops/scripts/metrics/capture_metrics.py\`
- \`ops/scripts/metrics/update_dashboard.py\`
- \`work/collaboration/AGENT_STATUS.md\`
- \`work/collaboration/HANDOFFS.md\`
- \`work/collaboration/WORKFLOW_LOG.md\`
- \`ops/scripts/metrics/README.md\` (usage documentation)
- \`work/reports/logs/build-automation/YYYY-MM-DDTHHMM-metric-capture-implementation.md\`

**Agent:** build-automation  
**Priority:** normal
EOF
)"

# Issue 6: Assess Dynamic Dashboard Feasibility
create_issue \
  "Assess creating dynamic dashboard via stateless webservice" \
  "architecture,assessment,architect" \
  "low" \
  "$(cat <<'EOF'
## Description

Assess the feasibility of creating a dynamic dashboard using a simple stateless webservice that pulls orchestration information and displays it to users in real-time.

## Context

- Task file: \`work/collaboration/inbox/2025-11-26T0616-architect-assess-dynamic-dashboard.yaml\`
- Alternative to static markdown dashboard files
- PR comment: https://github.com/sddevelopment-be/quickstart_agent-augmented-development/pull/.../files#r2563371914

## Assessment Scope

Evaluate:
- Implementation effort and complexity
- Maintenance cost
- Value proposition vs static files
- Technology options (simple HTTP server, existing tools)
- Security considerations
- Deployment options (local, CI/CD integration)

## Acceptance Criteria

- [ ] Assessment completed and documented in ADR format
- [ ] Trade-offs clearly articulated: static files vs dynamic service
- [ ] Recommendation provided (implement, defer, or reject)
- [ ] If recommending implementation, include:
  - [ ] Rough effort estimate
  - [ ] Technology recommendations
  - [ ] Implementation approach
- [ ] Work log created

## Deliverables

- \`docs/architecture/adrs/ADR-XXX-dynamic-dashboard-assessment.md\`
- \`work/reports/logs/architect/YYYY-MM-DDTHHMM-dynamic-dashboard-assessment.md\`

**Agent:** architect  
**Priority:** low
EOF
)"

echo "✅ All issues created successfully!"
echo ""
echo "Epic: #$EPIC_NUMBER"
echo ""
echo "Next steps:"
echo "1. Review created issues at https://github.com/$REPO/issues"
echo "2. Agents can process tasks from work/collaboration/inbox/"
echo "3. Link GitHub issues to task completions"
