name: 'Setup Python Environment'
description: 'Sets up Python with dependency caching for orchestration and validation scripts'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'
  cache-key-prefix:
    description: 'Prefix for cache key'
    required: false
    default: 'pip'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
