name: Bug report
description: Create a report to help us improve our project
title: ''
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug
        A clear and concise description of what the bug is.

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - latest
        - 1.0.0
      description: What version are you using?
    validations:
      required: true

  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      options:
        - Linux
        - Windows
        - Mac
      description: Which OS are you using?
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS version
      description: Enter your OS version
      placeholder: version goes here

  - type: input
    id: jdk_version
    attributes:
      label: JDK version
      description: Enter your JDK version
      placeholder: version goes here

  - type: input
    id: maven_version
    attributes:
      label: Maven version
      description: Enter your Maven version
      placeholder: version goes here

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: reproduction_steps
    attributes:
      label: How to reproduce
      description: If applicable, add information on how to reproduce the problem.

  - type: input
    id: gist
    attributes:
      label: Gist to unit test showing the issue in action
      description: If possible, provide a link to a gist with a unit test displaying the faulty behaviour.
      placeholder: https://gist.github.com/...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

