# repo-outline.yaml — Structural Snapshot (Base)
# Purpose: machine-usable map for agents (structural, curator, lexical, diagrammer)

repo:
  name: {{REPO_NAME}}
  purpose: {{one-line purpose}}
  language: [{{primary_langs}}]
  license: {{SPDX_ID}}
  visibility: private # or public

ownership:
  codeowners:
    - handle: "@username"
      scope: ["src/**", "docs/**"]
  reviewers:
    - team: "architecture"
    - team: "docs"

conventions:
  versioning: semver # or calendar
  changelog: docs/CHANGELOG.md
  formatting:
    markdown: true
    code: true
  punctuation:
    em_dash: '---'
    smart_quotes: false

structure:
  folders:
    - path: src/
      purpose: "{{source code}}"
    - path: docs/
      purpose: "{{documentation}}"
    - path: scripts/
      purpose: "{{automation}}"
    - path: infra/
      purpose: "{{infra as code}}"
    - path: content/
      purpose: "{{site content}}"
    - path: test/
      purpose: "{{tests}}"
  key_files:
    - README.md
    - LICENSE
    - .editorconfig
    - .gitignore

surfaces:
  entry_points:
    - type: cli
      path: bin/{{name}}
      desc: "{{cli description}}"
    - type: service
      path: src/server.ts
      desc: "{{http service}}"
    - type: library
      path: src/index.ts
      desc: "{{public API}}"
  integrations:
    http: []
    messaging: []
    storage: []
  observability:
    logs: "{{location}}"
    metrics: "{{location}}"
    traces: "{{location}}"

pipelines:
  build:
    tool: "{{build tool}}"
    commands:
      - "{{cmd}}"
  test:
    unit: "{{framework}}"
    integration: "{{framework}}"
    coverage:
      tool: "{{tool}}"
      threshold: 0.8
  release:
    strategy: semver
    registry: "{{registry}}"
  ci:
    provider: github-actions
    workflows:
      - name: build-and-test
        path: .github/workflows/build.yml
        triggers: ["push", "pull_request"]

context:
  files:
    operational: context/operational-reference.md
    strategic: context/strategic-context.md
    commands: context/command-aliases.md
    bootstrap: context/system-bootstrap.md
    agents: AGENTS.md
  versions:
    operational: "v1.2.0"
    strategic: "v1.0.0"
    commands: "v1.1.0"
    bootstrap: "v1.0.0"

risks:
  known:
    - "{{risk description}}"
  mitigations:
    - "{{mitigation}}"

status:
  last_scanned: "{{ISO8601}}"
  confidence: 0.0 # 0.0–1.0 structural map confidence