#!/bin/sh
# Framework Packaging Script
# Version: 1.0.0
# Purpose: Package agent-augmented development framework as distributable zip
# Requirements: POSIX-compliant shell, find, zip, sha256sum

set -e

# Configuration
VERSION="${1:-dev}"
OUTPUT_DIR="${2:-.}"
PACKAGE_NAME="quickstart-framework-${VERSION}.zip"

# Core directories to include in distribution
CORE_DIRS=".github/agents docs/directives docs/guidelines docs/templates docs/architecture/adrs validation"

# Script directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUILD_DIR="${REPO_ROOT}/build/framework-${VERSION}"
FRAMEWORK_CORE="${BUILD_DIR}/framework_core"
SCRIPTS_DIR="${BUILD_DIR}/scripts"
META_DIR="${BUILD_DIR}/META"

echo "🎁 Framework Packaging Script"
echo "Version: ${VERSION}"
echo "Repository: ${REPO_ROOT}"
echo ""

# Clean and create build directory
if [ -d "${BUILD_DIR}" ]; then
    echo "🧹 Cleaning existing build directory..."
    rm -rf "${BUILD_DIR}"
fi

mkdir -p "${FRAMEWORK_CORE}" "${SCRIPTS_DIR}" "${META_DIR}"
echo "✅ Created build directory: ${BUILD_DIR}"

# Copy core directories
echo ""
echo "📦 Copying core directories..."
cd "${REPO_ROOT}"

for dir in ${CORE_DIRS}; do
    if [ -d "${dir}" ]; then
        echo "  - ${dir}"
        target_dir="${FRAMEWORK_CORE}/${dir}"
        mkdir -p "$(dirname "${target_dir}")"
        cp -r "${dir}" "${target_dir}"
    else
        echo "  ⚠️  Warning: ${dir} not found, skipping"
    fi
done

# Copy work scaffolds (empty directory structure)
echo "  - work/ scaffolds"
for subdir in inbox assigned done archive logs collaboration; do
    mkdir -p "${FRAMEWORK_CORE}/work/${subdir}"
    touch "${FRAMEWORK_CORE}/work/${subdir}/.gitkeep"
done

# Copy scripts
echo ""
echo "📜 Copying installation scripts..."
if [ -f "${REPO_ROOT}/scripts/framework_install.sh" ]; then
    cp "${REPO_ROOT}/scripts/framework_install.sh" "${SCRIPTS_DIR}/"
    chmod +x "${SCRIPTS_DIR}/framework_install.sh"
    echo "  ✅ framework_install.sh"
else
    echo "  ⚠️  framework_install.sh not found"
fi

if [ -f "${REPO_ROOT}/scripts/framework_upgrade.sh" ]; then
    cp "${REPO_ROOT}/scripts/framework_upgrade.sh" "${SCRIPTS_DIR}/"
    chmod +x "${SCRIPTS_DIR}/framework_upgrade.sh"
    echo "  ✅ framework_upgrade.sh"
else
    echo "  ⚠️  framework_upgrade.sh not found"
fi

# Generate MANIFEST.yml with checksums
echo ""
echo "🔐 Generating MANIFEST.yml with checksums..."
MANIFEST="${META_DIR}/MANIFEST.yml"

cat > "${MANIFEST}" << 'EOF'
# Framework Distribution Manifest
# Generated by framework_package.sh

framework_version: VERSION_PLACEHOLDER
packaged_at: TIMESTAMP_PLACEHOLDER
package_format: zip

core_files:
EOF

# Find all files in framework_core and generate checksums
cd "${FRAMEWORK_CORE}"
find . -type f | sort | while IFS= read -r file
do
    # Remove leading ./
    clean_path="${file#./}"
    
    # Calculate checksum
    checksum=$(sha256sum "${file}" | cut -d' ' -f1)
    
    # Get file mode
    if [ -x "${file}" ]; then
        mode="executable"
    else
        mode="regular"
    fi
    
    # Append to manifest
    cat >> "${MANIFEST}" << EOF
  - path: ${clean_path}
    sha256: ${checksum}
    mode: ${mode}
    scope: core
EOF
done

# Replace placeholders
sed -i "s/VERSION_PLACEHOLDER/${VERSION}/g" "${MANIFEST}"
sed -i "s/TIMESTAMP_PLACEHOLDER/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/g" "${MANIFEST}"

echo "  ✅ Generated MANIFEST.yml ($(grep -c "path:" "${MANIFEST}") files)"

# Create release notes template
echo ""
echo "📝 Creating release notes template..."
RELEASE_NOTES="${META_DIR}/RELEASE_NOTES.md"

cat > "${RELEASE_NOTES}" << EOF
# Release Notes: Framework v${VERSION}

**Release Date:** $(date -u +"%Y-%m-%d")  
**Package:** ${PACKAGE_NAME}

## What's New

- [List major features and improvements]
- [Reference relevant ADRs]

## Installation

\`\`\`bash
# Extract the package
unzip ${PACKAGE_NAME}

# Navigate to extracted directory
cd quickstart-framework-${VERSION}

# Run installation script
./scripts/framework_install.sh /path/to/your/project
\`\`\`

## Upgrading

If upgrading from a previous version:

\`\`\`bash
# Run upgrade script (dry-run first recommended)
./scripts/framework_upgrade.sh --dry-run /path/to/your/project

# Apply upgrade
./scripts/framework_upgrade.sh /path/to/your/project
\`\`\`

## Changes Since Previous Release

- See CHANGELOG.md for detailed changes
- Review ADR index for architectural decisions

## Known Issues

- [List any known issues or limitations]

## Support

For questions or issues, see docs/HOW_TO_USE/ documentation.
EOF

echo "  ✅ Created RELEASE_NOTES.md"

# Create upgrade notes template
UPGRADE_NOTES="${META_DIR}/UPGRADE_NOTES.md"
cat > "${UPGRADE_NOTES}" << EOF
# Upgrade Notes: Framework v${VERSION}

## Prerequisites

- Existing framework installation
- Backup of your project recommended

## Breaking Changes

- [List any breaking changes]

## Migration Steps

1. Review release notes
2. Run upgrade script with --dry-run
3. Review upgrade report and .framework-new files
4. Apply upgrade
5. Run Framework Guardian audit

## Post-Upgrade Validation

\`\`\`bash
# Run Guardian audit
python3 work/scripts/framework_guardian.py --mode audit --target .

# Review audit report
cat validation/FRAMEWORK_AUDIT_REPORT.md
\`\`\`

## Rollback Procedure

If issues occur:

1. Restore from backup
2. Or manually revert files using .bak files created during upgrade
EOF

echo "  ✅ Created UPGRADE_NOTES.md"

# Create package
echo ""
echo "📦 Creating zip package..."
cd "${BUILD_DIR}"
zip -r "${OUTPUT_DIR}/${PACKAGE_NAME}" . > /dev/null 2>&1
echo "  ✅ Created ${PACKAGE_NAME}"

# Calculate package checksum
cd "${OUTPUT_DIR}"
PACKAGE_CHECKSUM=$(sha256sum "${PACKAGE_NAME}" | cut -d' ' -f1)

# Generate package info
echo ""
echo "✨ Package Information:"
echo "  Name: ${PACKAGE_NAME}"
echo "  Size: $(du -h "${PACKAGE_NAME}" | cut -f1)"
echo "  SHA256: ${PACKAGE_CHECKSUM}"
echo "  Location: ${OUTPUT_DIR}/${PACKAGE_NAME}"
echo ""
echo "📄 Package contents:"
echo "  - framework_core/ (curated framework files)"
echo "  - scripts/ (install/upgrade scripts)"
echo "  - META/ (manifest, release notes, upgrade notes)"
echo ""
echo "✅ Packaging complete!"

# Cleanup build directory
rm -rf "${BUILD_DIR}"
echo "🧹 Cleaned up build directory"
